ToDo-Calendar/ToDo-Calendar/Controllers/FullWeekController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToDo_Calendar.Models;
using ToDo_Calendar.Business.Interfaces;
using ToDo_Calendar.Business.Classes;

namespace ToDo_Calendar.Controllers
{
    public class FullWeekController : Controller
    {
      
        // GET: FullWeek
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SelectedDay(int id)
        {
          
            TasksBusiness SelectTasks = new TasksBusiness();
            List<TasksModel> TaskList;
            TaskList = SelectTasks.SelectAll(id);
            TempData["SelectedDayID"] = id;

            return View(TaskList);
        }
        public ActionResult SelectedTask()
        {
            return View();

        }
        public ActionResult InsertNewTask(TasksModel obj)
        {
            int selectedDayID = Convert.ToInt32(TempData["SelectedDayID"]);
            TasksBusiness insertTask = new TasksBusiness();          
            obj.TaskDaysID = selectedDayID;        
            insertTask.Insert(obj);
            
            return RedirectToAction("SelectedDay",new { id = selectedDayID });
            
        }
        public ActionResult BackToSelectedDay()
        {
            int selectedDayID = Convert.ToInt32(TempData["SelectedDayID"]);
                      
            return RedirectToAction("SelectedDay", new { id = selectedDayID });

        }
        public ActionResult DeleteTask(int id)
        {
            TasksBusiness tb = new TasksBusiness();
            tb.Delete(id);
            int selectedDayID = Convert.ToInt32(TempData["SelectedDayID"]);


            return RedirectToAction("SelectedDay", new { id = selectedDayID });
        }
        public ActionResult EditSelectedTask(int id)
        {
            TasksBusiness task = new TasksBusiness();
            TempData["SelectedTaskID"] = id;

            return View(task.SelectSingle(id));
        }
        public ActionResult InsertEditedTask(TasksModel obj)
        {
            TasksBusiness task = new TasksBusiness();
            int selectedDayID = Convert.ToInt32(TempData["SelectedDayID"]);       
            obj.TaskID = Convert.ToInt32(TempData["SelectedTaskID"]);
            task.Update(obj);
           

            return RedirectToAction("SelectedDay", new { id = selectedDayID });
        }
    }
}

ToDo-Calendar/ToDo-Calendar/Views/FullWeek/EditSelectedTask.cshtml
@model ToDo_Calendar.Models.TasksModel
@{
    ViewBag.Title = "EditSelectedTask";
}

<div class="container day-header">
    <div>EDIT SELECTED TASK</div>
</div>

@using (Html.BeginForm("InsertEditedTask", "FullWeek"))
{

    <div id="form-container">
        <div id="edit-task-form">
            <input id="task-name-text" type="text" name="obj.TaskTitle" maxlength="20" required autocomplete="off" value="@Model.TaskTitle" />
            <br />
            <br />
            <input id="task-text-box" name="obj.TaskText" maxlength="150" required value="@Model.TaskText" autocomplete="off" wrap="true" />
        </div>
    </div>
        <div class="content" id="edit-navigation">

            <a class="go-back"  href="@Url.Action("BackToSelectedDay", "FullWeek")">| GO BACK </a>
            <button type="submit" class="add-task">| SAVE CHANGES</button>

        </div>
}

ToDo-Calendar/ToDo-Calendar/Views/FullWeek/SelectedDay.cshtml
@model IEnumerable<ToDo_Calendar.Models.TasksModel>
@{
    ViewBag.Title = "SelectedDay";
    
}
<body>
    <div class="container day-header">
        <div>TASKS FOR THIS DAY</div>
        <div class="content" id="go-back"><a class="go-back" href="@Url.Action("Index", "Home")">| GO BACK</a></div>
        <div id="new-task"><a href="@Url.Action("SelectedTask", "FullWeek")">| NEW TASK</a></div>
    </div>



    <div class="notes-container">
        @foreach (var item in Model)
        {
           
            <div class="notes">
                <div class="notes-title">@item.TaskTitle</div>
                <br /><br />
                <div class="notes-text">@item.TaskText</div>
                <div class="notes-nav">
                    <br /><br />
                    <a class="edit-task" href="@Url.Action("EditSelectedTask", "FullWeek",new { id = item.TaskID })">Edit <span id="line">|</span></a>                  
                    <a class="delete-task" href="@Url.Action("DeleteTask", "FullWeek",new { id = item.TaskID })">Delete</a>
                </div>
            </div>

        }

    </div>
    
</body>

ToDo-Calendar/ToDo-Calendar/Views/FullWeek/SelectedTask.cshtml
@{
    ViewBag.Title = "SelectedTask";
}
<body>
    <div class="container day-header">
        <div>CREATE NEW TASK</div>
    </div>
    @using (Html.BeginForm("InsertNewTask", "FullWeek"))
    {
        
        <div id="form-container">
            <div id="new-task-form">
                <input id="task-name-text" type="text" name="obj.TaskTitle" maxlength="20" required autocomplete="off" placeholder="Enter task name here..." />
                <br />
                <br />
                <textarea id="task-text-box" name="obj.TaskText" maxlength="150" required autocomplete="off" placeholder="Enter task information here..."></textarea>
            </div>
        </div>
        <div class="content" >

            <a class="go-back" href="@Url.Action("BackToSelectedDay", "FullWeek")">| GO BACK </a>
            <button type="submit" class="add-task">| ADD THIS TASK</button>

        </div>       
    }


</body>